from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    genres = (
        ('M', 'Masculin'),
        ('F', 'Féminin'),
    )
    pays_list =(
        ('Algeria', 'DZ'),
        ('Angola', 'AO'),
        ('Benin', 'BJ'),
        ('Botswana', 'BW'),
        ('Burkina Faso', 'BF'),
        ('Burundi', 'BI'),
        ('Cabo Verde', 'CV'),
        ('Cameroon', 'CM'),
        ('Central African Republic', 'CF'),
        ('Chad', 'TD'),
        ('Comoros', 'KM'),
        ('Congo (Congo-Brazzaville)', 'CG'),
        ('Democratic Republic of the Congo (Congo-Kinshasa)', 'CD'),
        ('Djibouti', 'DJ'),
        ('Egypt', 'EG'),
        ('Equatorial Guinea', 'GQ'),
        ('Eritrea', 'ER'),
        ('Eswatini (fmr. "Swaziland")', 'SZ'),
        ('Ethiopia', 'ET'),
        ('Gabon', 'GA'),
        ('Gambia', 'GM'),
        ('Ghana', 'GH'),
        ('Guinea', 'GN'),
        ('Guinea-Bissau', 'GW'),
        ('Ivory Coast', 'CI'),
        ('Kenya', 'KE'),
        ('Lesotho', 'LS'),
        ('Liberia', 'LR'),
        ('Libya', 'LY'),
        ('Madagascar', 'MG'),
        ('Malawi', 'MW'),
        ('Mali', 'ML'),
        ('Mauritania', 'MR'),
        ('Mauritius', 'MU'),
        ('Morocco', 'MA'),
        ('Mozambique', 'MZ'),
        ('Namibia', 'NA'),
        ('Niger', 'NE'),
        ('Nigeria', 'NG'),
        ('Rwanda', 'RW'),
        ('Sao Tome and Principe', 'ST'),
        ('Senegal', 'SN'),
        ('Seychelles', 'SC'),
        ('Sierra Leone', 'SL'),
        ('Somalia', 'SO'),
        ('South Africa', 'ZA'),
        ('South Sudan', 'SS'),
        ('Sudan', 'SD'),
        ('Tanzania', 'TZ'),
        ('Togo', 'TG'),
        ('Tunisia', 'TN'),
        ('Uganda', 'UG'),
        ('Zambia', 'ZM'),
        ('Zimbabwe', 'ZW'),
        ('France', 'FR'),
        ('Germany', 'DE'),
        ('Italy', 'IT'),
        ('Spain', 'ES'),
        ('United Kingdom', 'GB'),
        ('United States', 'US'),
        ('Canada', 'CA'),
        ('Australia', 'AU'),
        ('New Zealand', 'NZ'),
        ('India', 'IN'),
        ('China', 'CN'),
        ('Japan', 'JP'),
        ('South Korea', 'KR'),
        ('Brazil', 'BR'),
        ('Mexico', 'MX'),
        ('Argentina', 'AR'),
        ('Chile', 'CL'),
        ('Colombia', 'CO'),
        ('Peru', 'PE'),
        ('Venezuela', 'VE'),
        ('Russia', 'RU'),
        ('Ukraine', 'UA'),
        ('Poland', 'PL'),
        ('Czech Republic', 'CZ'),
        ('Hungary', 'HU'),
        ('Romania', 'RO'),
        ('Bulgaria', 'BG'),
        ('Greece', 'GR'),
        ('Turkey', 'TR'),
        ('Saudi Arabia', 'SA'),
        ('United Arab Emirates', 'AE'),
        ('Israel', 'IL'),
        ('Iran', 'IR'),
        ('Pakistan', 'PK'),
        ('Bangladesh', 'BD'),
        ('Sri Lanka', 'LK'),
        ('Nepal', 'NP'),
        ('Bhutan', 'BT'),
        ('Maldives', 'MV'),
        ('Afghanistan', 'AF'),
        ('Kazakhstan', 'KZ'),
        ('Uzbekistan', 'UZ'),
        ('Turkmenistan', 'TM'),
        ('Kyrgyzstan', 'KG'),
        ('Tajikistan', 'TJ'),
        ('Mongolia', 'MN'),
        ('North Korea', 'KP'),
        ('Vietnam', 'VN'),
        ('Thailand', 'TH'),
        ('Malaysia', 'MY'),
        ('Singapore', 'SG'),
        ('Indonesia', 'ID'),
        ('Philippines', 'PH'),
        ('Myanmar (Burma)', 'MM'), 
        ('Cambodia', 'KH'),
        ('Laos', 'LA'),
        ('Brunei', 'BN'),
        ('Timor-Leste', 'TL'),
        ('Papua New Guinea', 'PG'),
        ('Fiji', 'FJ'),
        ('Solomon Islands', 'SB'),
        ('Vanuatu', 'VU'),
        ('Samoa', 'WS'),
        ('Tonga', 'TO'),
        ('Kiribati', 'KI'),
        ('Marshall Islands', 'MH'),
        ('Micronesia', 'FM'),
        ('Palau', 'PW'),
        ('Nauru', 'NR'),
        ('Tuvalu', 'TV'),
        ('Antigua and Barbuda', 'AG'),
        ('Bahamas', 'BS'),
        ('Barbados', 'BB'),
        ('Belize', 'BZ'),
        ('Costa Rica', 'CR'),
        ('Cuba', 'CU'),
        ('Dominica', 'DM'),
        ('Dominican Republic', 'DO'),
        ('El Salvador', 'SV'),
        ('Grenada', 'GD'),
        ('Guatemala', 'GT'),
        ('Haiti', 'HT'),
        ('Honduras', 'HN'),
        ('Jamaica', 'JM'),
        ('Nicaragua', 'NI'),
        ('Panama', 'PA'),
        ('Saint Kitts and Nevis', 'KN'),
        ('Saint Lucia', 'LC'),
        ('Saint Vincent and the Grenadines', 'VC'),
        ('Trinidad and Tobago', 'TT'),
        ('Belarus', 'BY'),
        ('Lithuania', 'LT'),
        ('Latvia', 'LV'),
        ('Estonia', 'EE'),
        ('Slovakia', 'SK'),
        ('Slovenia', 'SI'),
        ('Croatia', 'HR'),
        ('Bosnia and Herzegovina', 'BA'),
        ('Serbia', 'RS'),
        ('Montenegro', 'ME'),
        ('North Macedonia', 'MK'),
        ('Albania', 'AL'),
        ('Kosovo', 'XK'),
        ('Malta', 'MT'),
        ('Cyprus', 'CY'),
        ('Iceland', 'IS'),
        ('Ireland', 'IE'),
        ('Luxembourg', 'LU'),
        ('Monaco', 'MC'),
        ('Liechtenstein', 'LI'),
        ('San Marino', 'SM'),
        ('Andorra', 'AD'),
        ('Vatican City', 'VA'),
        ('Greenland', 'GL'),
        ('Faroe Islands', 'FO'),
        ('Svalbard and Jan Mayen', 'SJ'),
        ('Armenia', 'AM'),
        ('Azerbaijan', 'AZ'),
        ('Georgia', 'GE'),
        ('Moldova', 'MD'),
        ('Belize', 'BZ'),
        ('Guyana', 'GY'),
        ('Suriname', 'SR'),
        ('French Guiana', 'GF'),
        ('Falkland Islands', 'FK'),
        ('South Georgia and the South Sandwich Islands', 'GS'),
        ('Bouvet Island', 'BV'),
        ('Heard Island and McDonald Islands', 'HM'),
        ('British Indian Ocean Territory', 'IO'),
        ('Christmas Island', 'CX'),
        ('Cocos (Keeling) Islands', 'CC'),
        ('Norfolk Island', 'NF'),
        ('Pitcairn Islands', 'PN'),
        ('Saint Helena, Ascension and Tristan da Cunha', 'SH'),
        ('South Sudan', 'SS'),
        ('Western Sahara', 'EH'),
        ('Syria', 'SY'),
        ('Yemen', 'YE'),
        ('Iraq', 'IQ'),
        ('Kuwait', 'KW'),
        ('Bahrain', 'BH'),
        ('Qatar', 'QA'),
        ('Oman', 'OM'),
        ('Jordan', 'JO'),
        ('Lebanon', 'LB'),
        ('Palestine', 'PS'),
    )
    genre = models.CharField(max_length=1, choices=genres, default='F')
    datenaissance = models.DateField(verbose_name='Date de naissance', auto_now=False, auto_now_add=False, null= True, blank=True)
    pays = models.CharField(
        verbose_name="pays",
        max_length=2,
        choices=tuple(dict((code, name) for name, code in pays_list).items()),
        default='CD',
    )
    province = models.CharField(verbose_name="Province",max_length=100, null=True, blank=True)
    ville = models.CharField(verbose_name='ville', max_length=150, null=True, blank=True)
    Adresse = models.CharField(verbose_name='Adresse', max_length=150, null=True, blank=True)
    email = models.EmailField(verbose_name='Email', max_length=254, null=True, blank= True)
    date_Inscription= models.DateField(verbose_name='Date d\'inscription', auto_now_add=True)
    telephone = models.CharField(verbose_name='Telephone', max_length=20, null=True, blank=True) 
    
