# Generated by Django 6.1.1 on 2026-09-30 19:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='nom programme')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_structure', models.CharField(max_length=100, verbose_name='Nom de la structure')),
                ('type_structure', models.CharField(choices=[('ONG', 'ONG'), ('ASBL', 'ASBL')], max_length=100, verbose_name='type de structure')),
                ('email', models.EmailField(max_length=200, verbose_name='Email du partenaire')),
                ('contact', models.CharField(max_length=20, verbose_name='Contact partenaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sponsorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField()),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B2B.partenaires')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='B2B.programme')),
            ],
        ),
    ]
