# Generated by Django 6.1.1 on 2026-09-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CycleMenstruel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_cycle', models.PositiveIntegerField(verbose_name='Durée du cycle (en jours)')),
                ('ovulation_date', models.DateField(blank=True, null=True, verbose_name="Date d'ovulation")),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='Menstruation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('estimation_prochaine_menstruation', models.DateField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menstruations', to='suivi_regles.cyclemenstruel', verbose_name='Cycle')),
            ],
        ),
        migrations.CreateModel(
            name='RessentirSymptome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensite', models.PositiveSmallIntegerField(default=1)),
                ('menstruation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_regles.menstruation')),
                ('symptome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suivi_regles.symptome')),
            ],
            options={
                'unique_together': {('menstruation', 'symptome')},
            },
        ),
        migrations.AddField(
            model_name='menstruation',
            name='symptomes',
            field=models.ManyToManyField(blank=True, through='suivi_regles.RessentirSymptome', to='suivi_regles.symptome'),
        ),
    ]
