# Generated by Django 6.1.1 on 2026-09-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=1)),
                ('datenaissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('pays', models.CharField(choices=[('DZ', 'Algeria'), ('AO', 'Angola'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cabo Verde'), ('CM', 'Cameroon'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('KM', 'Comoros'), ('CG', 'Congo (Congo-Brazzaville)'), ('CD', 'Democratic Republic of the Congo (Congo-Kinshasa)'), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('SZ', 'Eswatini (fmr. "Swaziland")'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GH', 'Ghana'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('CI', 'Ivory Coast'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('ST', 'Sao Tome and Principe'), ('SN', 'Senegal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('SS', 'South Sudan'), ('SD', 'Sudan'), ('TZ', 'Tanzania'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('UG', 'Uganda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('GB', 'United Kingdom'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('IN', 'India'), ('CN', 'China'), ('JP', 'Japan'), ('KR', 'South Korea'), ('BR', 'Brazil'), ('MX', 'Mexico'), ('AR', 'Argentina'), ('CL', 'Chile'), ('CO', 'Colombia'), ('PE', 'Peru'), ('VE', 'Venezuela'), ('RU', 'Russia'), ('UA', 'Ukraine'), ('PL', 'Poland'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('RO', 'Romania'), ('BG', 'Bulgaria'), ('GR', 'Greece'), ('TR', 'Turkey'), ('SA', 'Saudi Arabia'), ('AE', 'United Arab Emirates'), ('IL', 'Israel'), ('IR', 'Iran'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('LK', 'Sri Lanka'), ('NP', 'Nepal'), ('BT', 'Bhutan'), ('MV', 'Maldives'), ('AF', 'Afghanistan'), ('KZ', 'Kazakhstan'), ('UZ', 'Uzbekistan'), ('TM', 'Turkmenistan'), ('KG', 'Kyrgyzstan'), ('TJ', 'Tajikistan'), ('MN', 'Mongolia'), ('KP', 'North Korea'), ('VN', 'Vietnam'), ('TH', 'Thailand'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('ID', 'Indonesia'), ('PH', 'Philippines'), ('MM', 'Myanmar (Burma)'), ('KH', 'Cambodia'), ('LA', 'Laos'), ('BN', 'Brunei'), ('TL', 'Timor-Leste'), ('PG', 'Papua New Guinea'), ('FJ', 'Fiji'), ('SB', 'Solomon Islands'), ('VU', 'Vanuatu'), ('WS', 'Samoa'), ('TO', 'Tonga'), ('KI', 'Kiribati'), ('MH', 'Marshall Islands'), ('FM', 'Micronesia'), ('PW', 'Palau'), ('NR', 'Nauru'), ('TV', 'Tuvalu'), ('AG', 'Antigua and Barbuda'), ('BS', 'Bahamas'), ('BB', 'Barbados'), ('BZ', 'Belize'), ('CR', 'Costa Rica'), ('CU', 'Cuba'), ('DM', 'Dominica'), ('DO', 'Dominican Republic'), ('SV', 'El Salvador'), ('GD', 'Grenada'), ('GT', 'Guatemala'), ('HT', 'Haiti'), ('HN', 'Honduras'), ('JM', 'Jamaica'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('KN', 'Saint Kitts and Nevis'), ('LC', 'Saint Lucia'), ('VC', 'Saint Vincent and the Grenadines'), ('TT', 'Trinidad and Tobago'), ('BY', 'Belarus'), ('LT', 'Lithuania'), ('LV', 'Latvia'), ('EE', 'Estonia'), ('SK', 'Slovakia'), ('SI', 'Slovenia'), ('HR', 'Croatia'), ('BA', 'Bosnia and Herzegovina'), ('RS', 'Serbia'), ('ME', 'Montenegro'), ('MK', 'North Macedonia'), ('AL', 'Albania'), ('XK', 'Kosovo'), ('MT', 'Malta'), ('CY', 'Cyprus'), ('IS', 'Iceland'), ('IE', 'Ireland'), ('LU', 'Luxembourg'), ('MC', 'Monaco'), ('LI', 'Liechtenstein'), ('SM', 'San Marino'), ('AD', 'Andorra'), ('VA', 'Vatican City'), ('GL', 'Greenland'), ('FO', 'Faroe Islands'), ('SJ', 'Svalbard and Jan Mayen'), ('AM', 'Armenia'), ('AZ', 'Azerbaijan'), ('GE', 'Georgia'), ('MD', 'Moldova'), ('GY', 'Guyana'), ('SR', 'Suriname'), ('GF', 'French Guiana'), ('FK', 'Falkland Islands'), ('GS', 'South Georgia and the South Sandwich Islands'), ('BV', 'Bouvet Island'), ('HM', 'Heard Island and McDonald Islands'), ('IO', 'British Indian Ocean Territory'), ('CX', 'Christmas Island'), ('CC', 'Cocos (Keeling) Islands'), ('NF', 'Norfolk Island'), ('PN', 'Pitcairn Islands'), ('SH', 'Saint Helena, Ascension and Tristan da Cunha'), ('EH', 'Western Sahara'), ('SY', 'Syria'), ('YE', 'Yemen'), ('IQ', 'Iraq'), ('KW', 'Kuwait'), ('BH', 'Bahrain'), ('QA', 'Qatar'), ('OM', 'Oman'), ('JO', 'Jordan'), ('LB', 'Lebanon'), ('PS', 'Palestine')], default='CD', max_length=2, verbose_name='pays')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Province')),
                ('ville', models.CharField(blank=True, max_length=150, null=True, verbose_name='ville')),
                ('Adresse', models.CharField(blank=True, max_length=150, null=True, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_Inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telephone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
