# Generated by Django 6.1.1 on 2026-09-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule_abonnement', models.CharField(choices=[('FREEMIUM', 'Freemium'), ('PREMIUM', 'Premium'), ('BUSINESS', 'Business')], max_length=20, verbose_name='type_abonnement')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen_payement', models.CharField(max_length=50, verbose_name='moyen_payement')),
                ('date_paye', models.DateField(blank=True, null=True)),
                ('payement_statut', models.CharField(choices=[('Reussi', 'Reussi'), ('En attente', 'En attente'), ('Echoue', 'Echoue')], max_length=20, verbose_name='payement statut')),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payements', to='payements.abonnement')),
            ],
        ),
    ]
